name: build-m2tw-modding-tool

on: [push]

jobs:
  build:

    runs-on: windows-2022
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup .net
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Setup dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build DaC Launcher
      - name: Build
        run: ./Build.ps1 -shouldZip "True"

      # Upload build artifact
      - uses: actions/upload-artifact@v4
        with:
          name: "M2TW-Modding-Tool--${{ github.workflow_sha }}"
          path: D:\a\ModdingTool\ModdingTool\ModdingTool.zip
